### ISSUE TITLE
LCtech relais module hardware panopticum

### ISSUE THREAD

**Issue by wolfgangr** [WelterRocks/Sonoff-Tasmota#5]
I'd like to invite people to post information on their specifc flavours of LCtech 1/2/4 relais modules and their clones here
'=============================
**Have you look for this feature in other issues and in the wiki?**
Nope, this is an endeavour to collect imformation that might flow into a wiki :-)

**Is your feature request related to a problem? Please describe.**
issue #4  , but there may be others

**Describe the solution you'd like**
A Wiki page where people can identify the favor of clone they recieved from China, togehter with related configurations, quirks and workarounds

**Describe alternatives you've considered**
get lost in google, ebay, alibaba...

**Comment by wolfgangr** [comment]
https://www.ebay.de/itm/323518033341
ESP8266 DC 5/12/32/220V WiFi Wireless Switch Relais Modul Smart Home Automation
12V 4-CH ESP8266 WIFI Relay
'============
tried to upload an image now...
hm.... encounterd a github bug??
when I try to uplaod a file it says
"Something went really wron, and we can't process that file. Try again."
... too early for a beer, I'm afraid .....

**Comment by WelterRocks** [comment]
Hi,

As I told before in Issue #4, I would suggest to move to WESPOTA, because we will do some excessive code rewrites there, to support as many devices as possible. So I would like to merge your changes to WESPOTA, in order to use that project as a base for a new way of driver handling.

It is planned to introduce driver separation in vendor, device, subdevice. For example: In the future you could select Sonoff / ITEAD as vendor and will get a list of available modules in a subselect. That will make a complete rewrite of the driver sections, neccessary. 

Also I would like to have native ESP support and a selector for usable GPIOs and their function. That will give the user more control over generic projects.

**Comment by WelterRocks** [comment]
Please move to WESPOTA (https://github.com/VerboteneZone/WESPOTA. Because, I will continue work there, after I get out of this LTE eating hospital.

**Comment by wolfgangr** [comment]
Hi Oliver,

good luck for your Health and thousand thanks for the fork :-)
I think Thmoas Arends already begged for it...



On Wed, 16 Jan 2019 01:38:46 -0800
Oliver Welter <notifications@github.com> wrote:

> Please move to WESPOTA (https://github.com/VerboteneZone/WESPOTA.
> Because, I will continue work there, after I get out of this LTE
> eating hospital.
> 



-- 
Wolfgang Rosner
